# Generated by Django 5.1.3 on 2024-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MBTIType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=4)),
                ('description', models.TextField()),
                ('logic', models.IntegerField()),
                ('imagination', models.IntegerField()),
                ('discipline', models.IntegerField()),
            ],
        ),
    ]
