# Generated by Django 6.0.5 on 2026-05-18 21:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mbtitype',
            name='discipline',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mbtitype',
            name='imagination',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mbtitype',
            name='logic',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='mbtitype',
            name='name',
            field=models.CharField(max_length=4, unique=True),
        ),
        migrations.AddConstraint(
            model_name='mbtitype',
            constraint=models.CheckConstraint(condition=models.Q(('logic__gte', 0), ('logic__lte', 100)), name='mbti_logic_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='mbtitype',
            constraint=models.CheckConstraint(condition=models.Q(('imagination__gte', 0), ('imagination__lte', 100)), name='mbti_imagination_between_0_100'),
        ),
        migrations.AddConstraint(
            model_name='mbtitype',
            constraint=models.CheckConstraint(condition=models.Q(('discipline__gte', 0), ('discipline__lte', 100)), name='mbti_discipline_between_0_100'),
        ),
    ]
